### ISSUE TITLE
Cant bind event after removing whitespace

### ISSUE THREAD

**Issue by Xing-He** [aokiken/vue-remove-whitespace#10]
Hey friend,

This lib is very nice, but i found something could be a problem when worked with the event, maybe it can't replace elements with InnerHTML directly.

**Comment by aokiken** [comment]
Hi @Xing-He 

Currently only "inserted" is used

https://github.com/aokiken/vue-remove-whitespace/blob/ed085a17bb1876ad558192a462c6b8d7029ea035/index.js#L3-L7

Should "update" also be support?

ref https://vuejs.org/v2/guide/custom-directive.html#Hook-Functions

**Comment by Xing-He** [comment]
If you remove white-space on 'update' hook, it will call hook after every updated.
How about this [vue-tight](https://github.com/ianpurvis/vue-tight/blob/master/src/tighten.js)?

**Comment by aokiken** [comment]
I remembered that I try with on 'update' hook :joy:
I try fix it, Thx:)

**Comment by aokiken** [comment]
Hi, @Xing-He 

> This lib is very nice, but i found something could be a problem when worked with the event, maybe it can't replace elements with InnerHTML directly.

Can I confirm this?

For example, codesandbox, codepen

**Comment by Xing-He** [comment]
something like this.

https://codesandbox.io/s/infallible-mclean-9c1p3

**Comment by aokiken** [comment]
Thanks, I was able to confirm.

**Comment by aokiken** [comment]
@Xing-He fix it?
https://codesandbox.io/s/blissful-lamport-o668p
